kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: install
  namespace: fncm-install
  labels:
    app: fncm-install
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-cephfs # Replace with your own
  volumeMode: Filesystem
