apiVersion: v1
data:
  openldap.fncm-openldap.svc.cluster.local_ldap_non_external_verify.current_reconcile_checksum: ZTk4N2I4MDNjMTUxNjM0MzUzYTMyNDg1MjUyMGZiZmQ3NTg0NTQ1MA==
  openldap.fncm-openldap.svc.cluster.local_ldap_non_external_verify.last_reconcile_checksum: ZTk4N2I4MDNjMTUxNjM0MzUzYTMyNDg1MjUyMGZiZmQ3NTg0NTQ1MA==
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-07T11:50:11Z"
  name: ibm-cp4ba-ldap-info-cm
  namespace: fncm
  ownerReferences:
  - apiVersion: fncm.ibm.com/v1
    kind: FNCMCluster
    name: fncmdeploy
    uid: cb5532ab-ef6b-4073-8fee-ad0ffa28d6a9
  resourceVersion: "76129250"
  uid: 7a538e4a-34bf-4832-bd4d-71d386fb9772