apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secret
  namespace: fncm
  labels:
    app: fncm
    managed-by: argocd
type: Opaque
stringData:
  ldapUsername: "Administrator@home.local"
  ldapPassword: "vagrant"
