kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgresql-privileged
  namespace: fncm-postgresql
  labels:
    app: fncm-postgresql
subjects:
  - kind: ServiceAccount
    name: default
    namespace: fncm-postgresql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
