kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openldap-data
  namespace: fncm-openldap
  labels:
    app: fncm-openldap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-cephfs # Replace with your own
  volumeMode: Filesystem
