kind: Service
apiVersion: v1
metadata:
  name: openldap
  namespace: fncm-openldap
  labels:
    app: fncm-openldap
spec:
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: ldap-port
  type: NodePort
  selector:
    app: fncm-openldap
