apiVersion: v1
data:
  instance_ids: '[]'
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-07T12:14:46Z"
  labels:
    app: iccsap
    component: iccsap-config
  name: iccsap-instances-config
  namespace: fncm
  ownerReferences:
  - apiVersion: fncm.ibm.com/v1
    kind: FNCMCluster
    name: fncmdeploy
    uid: cb5532ab-ef6b-4073-8fee-ad0ffa28d6a9
  resourceVersion: "76137857"
  uid: 131f9bb3-f705-4e62-acf8-24f90c2aaa47